Repository papanito/ansible-role-cloudflared, pull requests merged in 2022-07, with the labels that each got.

#52 fix: missing "systemd_filename" declaration when tag "cf_configure" is used
  tasks/main.yml
Labels: bug

#53 ci: change branch of ansible-lint-action
  .ansible-lint
  .github/workflows/build.yml
  .github/workflows/release.yml
  tests/inventory.local.yml
  tests/local copy.yml
Labels: ci

#54 meta: Update changelog, bump version
  CHANGELOG.md
  VERSION
Labels: bug

#55 feat: handle load balancer setup
  README.md
  tasks/create_routes.yml
  tasks/create_routes_lb.yml
  tasks/main.yml
  templates/config.yml.j2
Labels: bug, enhancement

#56 meta: Update changelog, bump version
  CHANGELOG.md
  VERSION
Labels: release
